### ISSUE TITLE
Outdated repository links for frame-support and frame-system

### ISSUE THREAD

**Issue by Endericedragon** [substrate-developer-hub/substrate-docs#2086]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

Hello there. I am following the tutorial of building a collectible workshop to build my pallet. However, I believe that some code pieces in the tutorial are incorrect or outdated. More tangibly, in the webpage [Create a new pallet](https://docs.substrate.io/tutorials/collectibles-workshop/03-create-pallet/), the configurations for frame-support and frame-system is incorrect.
The incorrect code is as follows:

```toml
[dependencies]
frame-support = { default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "polkadot-v1.0.0"}
frame-system = { default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "polkadot-v1.0.0" }
```

When I used these codes, I got an error message from cargo, telling me that cargo cannot find the branch named "polkadot-v1.0.0".However, if I changed the "git" property from "https://github.com/paritytech/polkadot-sdk.git" to "https://github.com/paritytech/substrate.git", the error message disappeared and everything looked fine now.

### Steps to reproduce the problem

Just follow the steps in the webpage [Create a new pallet](https://docs.substrate.io/tutorials/collectibles-workshop/03-create-pallet/), and the cargo would show the error message when you try to run `cargo build --package collectibles`.
