### ISSUE TITLE
Frontmatter Keywords Convention

### ISSUE THREAD

**Issue by imadarai** [substrate-developer-hub/substrate-docs#302]
I'm getting the following error in dev-environment 
```
Mdx.frontmatter.keywords:
 - type: array
   value: [ ..., 'collators', ... ]
 - type: string
   value: 'client, wasm, rpc, node'
```

This is mainly the result of different files using different types.  
Currently we don't do much with Keywords, other than just pass the info to LunrIndex for scoring.  But this will become a bigger problem as we move forward.  We should decide if this is going to be an `array` or `string` and then just stick with it.  I personally prefer an `array` of strings, as it'll be a bit easier to work with when it comes to filtering, search, etc.  

Currently some documents have this, while the others don't.  

```
null
null
null
null
template, contribute, style guide
contribute, style guide, bounties
contribute, style guide
contribute, style guide
node, client, tooling
runtime, tooling
[
  'collators',
  'parachains',
  'upgrade',
  'cumulus',
  'storage',
  'migration'
]
storage migration, testing, runtime, tooling
[
  'collator',
  'parachain',
  'cumulus',
  'design',
  'selection',
  'economic',
  'game theory'
]
```

Think we should surface this and perhaps have a pass to update it across all docs.
